# The URL the site will be built for
base_url = "https://michaelkennedy.dev"

# Whether to automatically compile all Sass files in the sass directory
# compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Michael Kennedy"
description = "A personal website for a new graduate software developer"
profile_picture = "images/profile_picture.png"
header_image = "images/hero_image.jpg"
stylesheet = "main.css"
copyright = "Michael Kennedy © 2021"
resume="MichaelKennedy_Resume.pdf"


biography_title="Hi, I'm Michael"
biography="I am a recent graduate of Western Washington University's Computer Science program with a Communication Studies minor. I am an inquisitive and hard working individual who enjoys any opportunity to further his knowledge and abilities. I am currently based in the beautiful Bellingham, WA, seeking either hybrid or remote employment as a Software Engineer. Through my education, I've been fortunate to have worked on all types of projects — mobile, video games, web development, systems development, etc. I've found that I enjoy creating mobile applications, and working with stakeholders to create software for their needs. There is something about the tactile experience of interacting with a piece of software I wrote that I find incredibly satisfying. With that said, I'm open to any opportunities that will help me further my professional career. In my free time, I enjoy exploring Washington, playing classical guitar, photography, and making things with my hands. Photography allows me to shut off that part of my brain that wants to be analytical and allows me to enjoy the natural beauty of my surroundings. I've been playing guitar for most of my life, and I enjoy the elegance of classical music."

navbar_links = [
    { url="/", title="Home", target=""},
    { url="/projects", title="Projects", target=""},
    { url="/photography", title="Photography", target=""},
    { url="/resume", title="Resume", target=""},
    { url="https://github.com/xNS5", title="Github", target="_blank"},
    { url="https://www.linkedin.com/in/mw-kennedy/", title="Linkedin", target="_blank"},
    { url="/contact", title="Contact", target=""},
]

footer_links = [
    { url="https://github.com/xNS5", title="Github Repository URL", css_class= "icon brands alt fa-github"},
    { url="https://www.linkedin.com/in/mw-kennedy/", title="Linkedin URL", css_class="icon brands alt fa-linkedin"},
    { url="mailto:michael@michaelkennedy.dev", title="Email Link", css_class="icon solid alt fa-envelope"}
]

