# The URL the site will be built for
base_url = "https://michaelkennedy.dev"

# Whether to automatically compile all Sass files in the sass directory
# compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Michael Kennedy"
description = "A personal webiste for a soon-to-graduate software developer"
profile_picture = "profile_picture.png"
stylesheet = "site.css"
copyright = "Michael Kennedy © 2021"

navbar_links = [
    { url="/", title="Home", target=""},
    { url="/projects", title="Projects", target=""},
    { url="/photography", title="Photography", target=""},
    { url="/resume", title="Resume", target=""},
    { url="https://github.com/xNS5", title="Github", target="_blank"},
    { url="https://www.linkedin.com/in/mw-kennedy/", title="Linkedin", target="_blank"},
]

