# The URL the site will be built for
base_url = "https://michaelkennedy.dev/"

# Whether to automatically compile all Sass files in the sass directory
# compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Michael Kennedy"
description = "A personal website for a new graduate software developer"
profile_picture = "images/profile_picture.png"
header_image = "images/hero_image.jpg"
stylesheet = "main.css"
favicon = "code-black.ico"
copyright = "Michael Kennedy © 2021"
resume="MichaelKennedy_Resume.pdf"
validation_server="https://fastapi-recaptcha.herokuapp.com/v1/"

navbar_links = [
    { url= "", title="Home", target=""},
    { url="projects", title="Projects", target=""},
#     { url="photography", title="Photography", target=""},
    { url="resume", title="Resume", target=""},
    { url="https://github.com/xNS5", title="Github", target="_blank"},
    { url="https://www.linkedin.com/in/mw-kennedy/", title="Linkedin", target="_blank"},
    { url="contact", title="Contact", target=""},
]

footer_links = [
    { url="https://github.com/xNS5", title="Github Repository URL", css_class= "icon brands alt fa-github"},
    { url="https://www.linkedin.com/in/mw-kennedy/", title="Linkedin URL", css_class="icon brands alt fa-linkedin"},
    { url="mailto:michael@michaelkennedy.dev", title="Email Link", css_class="icon solid alt fa-envelope"}
]

